
package coffee.michel.sebcord.bot.ui.second;

import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.orderedlayout.FlexLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route(value = "first", layout = Cat2MainContainer.class)
public class Cat2ViewFirst extends VerticalLayout {
	private static final long serialVersionUID = -2653637655434962690L;

	public Cat2ViewFirst() {
		super();
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.h3 = new H3();
		this.flexLayout = new FlexLayout();
		this.itemDiv = new Div();
		this.itemDiv2 = new Div();
		this.itemDiv3 = new Div();
		this.itemDiv4 = new Div();
		this.itemDiv5 = new Div();

		this.setMinHeight("0");
		this.setSpacing(false);
		this.getStyle().set("overflow-x", "hidden");
		this.getStyle().set("overflow-y", "auto");
		this.h3.setText("images");
		this.flexLayout.setWrapMode(FlexLayout.WrapMode.WRAP);
		this.itemDiv.setClassName("my-item");
		this.itemDiv2.setClassName("my-item");
		this.itemDiv3.setClassName("my-item");
		this.itemDiv4.setClassName("my-item");
		this.itemDiv5.setClassName("my-item");

		this.itemDiv.setWidth("200px");
		this.itemDiv.setHeight("200px");
		this.itemDiv2.setWidth("200px");
		this.itemDiv2.setHeight("200px");
		this.itemDiv3.setWidth("200px");
		this.itemDiv3.setHeight("200px");
		this.itemDiv4.setWidth("200px");
		this.itemDiv4.setHeight("200px");
		this.itemDiv5.setWidth("200px");
		this.itemDiv5.setHeight("200px");
		this.flexLayout.add(this.itemDiv, this.itemDiv2, this.itemDiv3, this.itemDiv4, this.itemDiv5);
		this.h3.setSizeUndefined();
		this.flexLayout.setSizeFull();
		this.add(this.h3, this.flexLayout);
		this.setSizeUndefined();
	} // </generated-code>

	// <generated-code name="variables">
	private FlexLayout flexLayout;
	private Div        itemDiv, itemDiv2, itemDiv3, itemDiv4, itemDiv5;
	private H3         h3;
	// </generated-code>

}
