
package coffee.michel.sebcord.ui.second;

import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route(value = "overview", layout = CommandsContainer.class)
public class CommandsOverview extends VerticalLayout {
	private static final long serialVersionUID = 8518324137441769109L;

	public CommandsOverview() {
		super();
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.lblContent = new Label();

		this.lblContent.setText("Commands");
		this.lblContent.getStyle().set("font-size", "5em");

		this.lblContent.setSizeUndefined();
		this.add(this.lblContent);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private Label lblContent;
	// </generated-code>

}
